project:
  type: website
website:
  title: "Vianey Villegas"
  google-analytics: "G-PY2V7X0XT1"
  navbar:
    background: "#f7dce5"
    foreground: "#5b3f45"
    left:
    - href: index.html

      text: Home

    - href: projects.html

      text: Marketing Projects

    - href: digitalmarketing.html

      text: Digital Marketing

    - href: dashboard.html

      text: Dashboards

    - href: googleanalytics.html

      text: Google Analytics

    - href: revealjspresentation.html

      text: Revealjs Presentation Experience
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

